### ISSUE TITLE
Добавить бейджик с покрытием кода в README.md

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/history#41]
пример https://github.com/objectionary/eo?tab=readme-ov-file

**Comment by sas2job** [comment]
> на сайте еще такая инструкция
> 
> ```
> - name: Upload coverage reports to Codecov
>     uses: codecov/codecov-action@v4.0.1
>     with:
>       token: ${{ secrets.CODECOV_TOKEN }}
> ```

К сожалению доступа к  CI pipeline github у меня нет

**Comment by sas2job** [comment]
@sergio-fry Можешь скинуть ссылку из настроек?
![image](https://github.com/sergio-fry/history/assets/22750893/39157251-81c3-443d-9753-8ee490d55b14)

**Comment by sergio-fry** [comment]
вот такое нашел

```
[![codecov](https://codecov.io/gh/sergio-fry/history/graph/badge.svg?token=T46MLVIHEE)](https://codecov.io/gh/sergio-fry/history)
```

**Comment by sergio-fry** [comment]
Сборка прошла, но покрытие не отбражается
<img width="664" alt="Screenshot 2024-05-28 at 14 11 45" src="https://github.com/sergio-fry/history/assets/70792/5132ce0e-ba67-4515-9faa-3b0e1752a2a0">

**Comment by sas2job** [comment]
@sergio-fry Как понимаю тут нужен доступ к travis чтобы он передавал параметры. 
https://github.com/sergio-fry/history/issues/41#issuecomment-2131148702

**Comment by sergio-fry** [comment]
сломан синтаксис CI https://github.com/sergio-fry/history/actions/runs/9271998910
