### ISSUE TITLE
Новый логотип

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/history#49]
Старого логотипа нет. Нужно придумать лого и добавить его в шапку и как favicon. Можно использовать AI генераторы

**Comment by o-200** [comment]
Привет, не хватает информации о проекте, что он из себя представляет. 
Без этого тяжело придумать лого, да и впринципе другим разработчикам не понятно что из себя представляет проект

**Comment by sergio-fry** [comment]
Согласен, вот тут есть описание https://github.com/HeavyTechRuby/history/wiki#за-дверью

**Comment by o-200** [comment]
Пришла идея что можно сделать логотип на здание Sanctum Sanctorum (Санктум_Санкторум), где в комиксах или фильмах Marvel живёт Доктор Стрэндж, имеющий власть над временем.

Что мне нравится - у здания красивое стекло в центре, которое можно использовать как логотип.
![image](https://github.com/HeavyTechRuby/history/assets/34093966/8fb37930-d619-4276-a166-54f48d7fec70)
![image](https://github.com/HeavyTechRuby/history/assets/34093966/9674b882-6b94-4115-abc1-61b3ef7290aa)

**Comment by sergio-fry** [comment]
красивое. можно еще посмотреть в сторону питерской архитектуры. Или совместить. Короче, мне нравится.

**Comment by o-200** [comment]
> питерской архитектуры.

сразу в голову приходит офис вк


![image](https://github.com/HeavyTechRuby/history/assets/34093966/f735784b-53fd-48cd-8067-954ab82daf5e)
![image](https://github.com/HeavyTechRuby/history/assets/34093966/aad7e266-3b89-4a9d-a726-63cd318a8209)

**Comment by sergio-fry** [comment]
тоже красиво, мне нравится

**Comment by RedShore117** [comment]
Приветствую, покрутил AI генераторы, возможно заинтересует
![logo_1](https://github.com/HeavyTechRuby/history/assets/122808567/410d0c4a-58ee-414d-9459-12a0c61e4acd)
![logo_2](https://github.com/HeavyTechRuby/history/assets/122808567/e28ff3d8-00d2-4c7a-ba64-4e018020caaa)
![logo_3](https://github.com/HeavyTechRuby/history/assets/122808567/d45fad6b-9cb5-4c64-b48e-842df4a8127e)

**Comment by sergio-fry** [comment]
Первые два похожи на лого, смотрятся хорошо.

**Comment by golifox** [comment]
Первые два действительно похожи на лого, но для лого слишком много деталей, которые в маленькой иконке не рассмотреть, можно их попробовать взять с запасом на будущее для ребрендинга - например сделать минималистичнее, либо заморочиться с этим сейчас

**Comment by o-200** [comment]
> слишком много деталей

можно нейронке отдать эти фотографии и попросить сделать их в минимализме.



@RedShore117, можешь попрововать такое сделать?

**Comment by RedShore117** [comment]
@o-200, на данный момент имею доступ только к шедевруму от яндекса, там нет функционала, отличного от генерации нового изображения.  У меня есть пара предложений - первое это попробовать сегенерить еще вариантов в минималистичном стиле,  второе  это удалить лишние детали из первого лого

**Comment by o-200** [comment]
> @o-200, на данный момент имею доступ только к шедевруму от яндекса, там нет функционала, отличного от генерации нового изображения. У меня есть пара предложений - первое это попробовать сегенерить еще вариантов в минималистичном стиле, второе это удалить лишние детали из первого лого

Хорошая идея. Самый главный пункт по моему мнению в выборе фотографии - то, как оно будет выглядеть в маленьком разрешении для favicon. Сгенерируй пожалуйста с учетом этого :+1:

**Comment by RedShore117** [comment]
Немного почтистил лого + превью как будет выглядеть фавикон
![logo_updated](https://github.com/HeavyTechRuby/history/assets/122808567/8451221b-e7a1-475e-bcf8-112bdabef251)
![favicon_look](https://github.com/HeavyTechRuby/history/assets/122808567/9d1b7032-3b93-4227-981f-d28a8a641850)

**Comment by o-200** [comment]
> Немного почтистил лого + превью как будет выглядеть фавикон ![logo_updated](https://private-user-images.githubusercontent.com/122808567/338187754-8451221b-e7a1-475e-bcf8-112bdabef251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjU5MDAsIm5iZiI6MTcxODAyNTYwMCwicGF0aCI6Ii8xMjI4MDg1NjcvMzM4MTg3NzU0LTg0NTEyMjFiLWU3YTEtNDc1ZS1iY2Y4LTExMmJkYWJlZjI1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMzIwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDI0MjBiYzMxNWFkYmRmMTc0ZGFjMDgwNjMwNzU2OTMxZTdiY2NmNjI2MjJkMWU3MTk2MzBlZGRlMmYwMTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-rug6xA0iuX9tFigRiDCk47-NgEgh-rSjFPvOlUFdUM) ![favicon_look](https://private-user-images.githubusercontent.com/122808567/338187798-9d1b7032-3b93-4227-981f-d28a8a641850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjU5MDAsIm5iZiI6MTcxODAyNTYwMCwicGF0aCI6Ii8xMjI4MDg1NjcvMzM4MTg3Nzk4LTlkMWI3MDMyLTNiOTMtNDIyNy05ODFmLWQyOGE4YTY0MTg1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMzIwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGZmMmE5ZGIyZTQ5M2I5YzhhMGQyMTBmY2QzNjNlMTFhMDRhNTI4ZGNjMzU1NzE3NTcyMDgyYWI5ZWFhNzA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gzeTkDtftpgxr3DM142Shao3JbMrjwIgFP7kkQxD5s8)

looks great! Есть желание её вставить в проект?)

**Comment by sergio-fry** [comment]
на мой вкус - круто! особенно для начала.

**Comment by RedShore117** [comment]
@o-200 да, я не против добавить
