### ISSUE TITLE
Перевести сценарии "F01 Аутентификация" на русский 

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/history#50]
Сейчас в features/F01-authentification.feature сценарий описан по-английски, а тут сценарии по-русски https://github.com/HeavyTechRuby/history/wiki/Features

Нужно перевести на русский

**Comment by o-200** [comment]
@sergio-fry добавь меня в assignee тут и на пулл реквесте (я не могу) и надо закрыть эту задачу
