### ISSUE TITLE
Добавить русскую локализацию

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/history#54]
Сейчас сайт локализация только английская

Необходимо добавить config/locales/ru.yml и перевести туда все строки из config/locales/en.yml. Кроме этого, нужно выставить русскую локаль по-умолчанию. Это касается и тестов features

**Comment by sk8higher** [comment]
Можно взять задачу?

**Comment by sergio-fry** [comment]
@sk8higher при упоминании нужно указывать closes #70, чтобы issue звакрывалась сама
