### ISSUE TITLE
Обсуждение истории

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/history#56]
Необходимо добавить возможность оставить комментарий к истории

```gherkin
Функция: F03 Обсуждения

    Сценарий: F03S01 Я, как пользователь, могу обсудить историю с другими пользователями.
```

**Comment by kairat-symanov** [comment]
Это создать сущность Comments ?

**Comment by sergio-fry** [comment]
Задача сформулирована с точки зрения БТ. Сущности нужно будет продумать самому. При этом, сами комментарии уже начали делать тут #65
