### ISSUE TITLE
Перейти на ghcr.io вместо docker hub

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/history#64]
Из-за блокировки ресурса для России, теперь нет возможности собрать образ локально. Необходимо предложить решение для разработчиков.

INFO https://habr.com/ru/news/818177/

Например, перейти на ghcr.io вместо docker hub. Или добавить mirror.

**Comment by sergio-fry** [comment]
Можно предложить вариант по проксированию через yandex, например.

**Comment by kairat-symanov** [comment]
Привет! Если не в России, то не надо ничего делать?

**Comment by o-200** [comment]
> Привет! Если не в России, то не надо ничего делать?

Если у тебя нормально создается контейнер, то ничего делать не надо. Задача исключительно для тех, у кого блок по айпи и кто не хочет использовать впн для скачивания образов

**Comment by sergio-fry** [comment]
В рамках данной задачи нужно предложить решение для разработчиков из России. Оно не должно ломать работу для тех, кто не в России

**Comment by sergio-fry** [comment]
Без этого нельзя выкатить обновления

**Comment by o-200** [comment]
@sergio-fry беру на себя

**Comment by o-200** [comment]
Docker hub уже несколько дней как разблокирован для России. Если за неделю ничего не поменяется, то закрываю задачу

https://tass.ru/ekonomika/20981429

**Comment by sergio-fry** [comment]
отличная новость. действительно
