### ISSUE TITLE
Настроить автовыкатку

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/history#68]
Сейчас выкатка осуществляется вручную командой с локального компа

Необходимо настроить автовыкатку из main

Сервис запущен на сервере с dokku

**Comment by petrolax** [comment]
А у нас есть какой-то registry?

**Comment by petrolax** [comment]
Хотя, нашёл ещё такой вариант: https://docs.docker.com/build/ci/github-actions/local-registry/
Можно задачу назначить на меня

**Comment by sergio-fry** [comment]
У нас используется dokku сервер, который развернут на моем сервере.

**Comment by sergio-fry** [comment]
Там выкатка производится через git push, после чего сервер сам собирает актуальный образ из dockerfile, что лежит в проекте.
