### ISSUE TITLE
Запускать отправку репорта coverage только в main

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/history#74]
Сейчас отправка coverage отчета отправляется в каждой ветке, но ENV доступна только в main, поэтому сборка падает

Необходимо настроить отправку только в protected branches

related #47

**Comment by sas2job** [comment]
@sergio-fry
Выполнять или брать другую задачу?

**Comment by sergio-fry** [comment]
@sas2job бери!
