### ISSUE TITLE
сверстать header

### ISSUE THREAD

**Issue by o-200** [HeavyTechRuby/history#84]
Для удобной навигации по сайту необходимо сделать header, который будет показываться на каждой странице сайта.

![image](https://github.com/HeavyTechRuby/history/assets/34093966/3be4768b-2496-4472-9d2d-55ef89114782)

**Comment by sergio-fry** [comment]
@o-200 из описания непонятно, что именно ожидается

**Comment by sergio-fry** [comment]
А что именно в этом header должно быть? Давай пропишем состав меню, что ли

**Comment by RedShore117** [comment]
Я возьму эту задачу, когда определимся с составом, я бы добавил страницу о проекте и возможно блок "Города" с листингом населенных пунктов в которых есть записи

**Comment by o-200** [comment]
Мне кажется что туда нужно сунуть кнопку "create history" и убрать её с главной страницы. Логотип должен быть 100%

**Comment by RedShore117** [comment]
> Мне кажется что туда нужно сунуть кнопку "create history" и убрать её с главной страницы. Логотип должен быть 100%

Лого там уже есть и кнопка домой, ну уже 4 кнопки как минимум можем предложить это Домой(главная), добавить историю, города, о проекте.  как вариант в дальнейшем туда можем добавить кнопку логина\разлогина
