### ISSUE TITLE
Выкатка должна происходить только после успешной сборки CI

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/history#95]
В рамках #79 добавлена автовыкатка. 

Сейчас выкатка производится параллельно с исполнением тестов и не зависит от успешности сборки

Необходимо запускать выкатку толко после успешного прохождения всех проверок

**Comment by petrolax** [comment]
Возьму на себя

**Comment by sergio-fry** [comment]
@petrolax так #96 я уже замерджил в main, выкатить не получается из-за ошибки.
